enable doctests for testing and coverage
but disable scanning django_extensions/mmongodb/ for test
since an issue with pymongo db; see https://github.com/mongodb/mongo-python-driver/pull/305
results in the following annoying error:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/sqrbass/Projects/django-extensions/.tox/py27-dj19/lib/python2.7/site-packages/pymongo/periodic_executor.py", line 130, in _shutdown_executors
    executors = list(_EXECUTORS)
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/sqrbass/Projects/django-extensions/.tox/py27-dj19/lib/python2.7/site-packages/pymongo/periodic_executor.py", line 130, in _shutdown_executors
    executors = list(_EXECUTORS)
TypeError: 'NoneType' object is not iterable