Fix: Issue #536
Following error condition triggers when there is None value for any DateField or DateTimeField. I.e. value == None

File "-/django_extensions/management/commands/dumpscript.py", line 718, in get_attribute_value
return "dateutil.parser.parse(\"%s\")" % value.isoformat()
AttributeError: 'NoneType' object has no attribute 'isoformat'

The proposed fix is to check the value against None before actually calling isoformat on the value.