Use // instead of # for comments in dot template
Comments using # and having leading whitespaces on dot file cause syntax
errors when trying to render it on an interactive viewer (xdot).

To replicate error:

- Create a Graphviz dot file using:

  python manage.py graph_models myappname > output.dot

- Open with xdot:

  xdot output.dot

  The following error will appear:

    Error: <stdin>:2: syntax error near line 2
    context:   >>>  # <<<  Dotfile by Django-Extensions graph_models